# Generated by Django 5.2.7 on 2025-10-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenedurl",
            name="alias",
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
